// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

public final class LoginProto {
  private LoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 userId = 1;</code>
     * @return Whether the userId field is set.
     */
    boolean hasUserId();
    /**
     * <code>optional int32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>optional string userName = 2;</code>
     * @return Whether the userName field is set.
     */
    boolean hasUserName();
    /**
     * <code>optional string userName = 2;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <code>optional string userName = 2;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional string userTel = 3;</code>
     * @return Whether the userTel field is set.
     */
    boolean hasUserTel();
    /**
     * <code>optional string userTel = 3;</code>
     * @return The userTel.
     */
    java.lang.String getUserTel();
    /**
     * <code>optional string userTel = 3;</code>
     * @return The bytes for userTel.
     */
    com.google.protobuf.ByteString
        getUserTelBytes();

    /**
     * <code>optional string userEmail = 4;</code>
     * @return Whether the userEmail field is set.
     */
    boolean hasUserEmail();
    /**
     * <code>optional string userEmail = 4;</code>
     * @return The userEmail.
     */
    java.lang.String getUserEmail();
    /**
     * <code>optional string userEmail = 4;</code>
     * @return The bytes for userEmail.
     */
    com.google.protobuf.ByteString
        getUserEmailBytes();

    /**
     * <code>optional string userPassword = 5;</code>
     * @return Whether the userPassword field is set.
     */
    boolean hasUserPassword();
    /**
     * <code>optional string userPassword = 5;</code>
     * @return The userPassword.
     */
    java.lang.String getUserPassword();
    /**
     * <code>optional string userPassword = 5;</code>
     * @return The bytes for userPassword.
     */
    com.google.protobuf.ByteString
        getUserPasswordBytes();

    /**
     * <code>optional bool userType = 6;</code>
     * @return Whether the userType field is set.
     */
    boolean hasUserType();
    /**
     * <code>optional bool userType = 6;</code>
     * @return The userType.
     */
    boolean getUserType();

    /**
     * <code>optional double userMoney = 7;</code>
     * @return Whether the userMoney field is set.
     */
    boolean hasUserMoney();
    /**
     * <code>optional double userMoney = 7;</code>
     * @return The userMoney.
     */
    double getUserMoney();

    /**
     * <code>optional string userCompany = 8;</code>
     * @return Whether the userCompany field is set.
     */
    boolean hasUserCompany();
    /**
     * <code>optional string userCompany = 8;</code>
     * @return The userCompany.
     */
    java.lang.String getUserCompany();
    /**
     * <code>optional string userCompany = 8;</code>
     * @return The bytes for userCompany.
     */
    com.google.protobuf.ByteString
        getUserCompanyBytes();

    /**
     * <code>optional string userHome = 9;</code>
     * @return Whether the userHome field is set.
     */
    boolean hasUserHome();
    /**
     * <code>optional string userHome = 9;</code>
     * @return The userHome.
     */
    java.lang.String getUserHome();
    /**
     * <code>optional string userHome = 9;</code>
     * @return The bytes for userHome.
     */
    com.google.protobuf.ByteString
        getUserHomeBytes();

    /**
     * <code>optional string userIp = 10;</code>
     * @return Whether the userIp field is set.
     */
    boolean hasUserIp();
    /**
     * <code>optional string userIp = 10;</code>
     * @return The userIp.
     */
    java.lang.String getUserIp();
    /**
     * <code>optional string userIp = 10;</code>
     * @return The bytes for userIp.
     */
    com.google.protobuf.ByteString
        getUserIpBytes();

    /**
     * <code>optional string userPos = 11;</code>
     * @return Whether the userPos field is set.
     */
    boolean hasUserPos();
    /**
     * <code>optional string userPos = 11;</code>
     * @return The userPos.
     */
    java.lang.String getUserPos();
    /**
     * <code>optional string userPos = 11;</code>
     * @return The bytes for userPos.
     */
    com.google.protobuf.ByteString
        getUserPosBytes();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      userName_ = "";
      userTel_ = "";
      userEmail_ = "";
      userPassword_ = "";
      userCompany_ = "";
      userHome_ = "";
      userIp_ = "";
      userPos_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              userTel_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              userEmail_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              userPassword_ = s;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              userType_ = input.readBool();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              userMoney_ = input.readDouble();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              userCompany_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              userHome_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              userIp_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              userPos_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoginProto.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoginProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoginProto.User.class, LoginProto.User.Builder.class);
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional int32 userId = 1;</code>
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>optional string userName = 2;</code>
     * @return Whether the userName field is set.
     */
    @java.lang.Override
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string userName = 2;</code>
     * @return The userName.
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userName = 2;</code>
     * @return The bytes for userName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERTEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object userTel_;
    /**
     * <code>optional string userTel = 3;</code>
     * @return Whether the userTel field is set.
     */
    @java.lang.Override
    public boolean hasUserTel() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string userTel = 3;</code>
     * @return The userTel.
     */
    @java.lang.Override
    public java.lang.String getUserTel() {
      java.lang.Object ref = userTel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userTel_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userTel = 3;</code>
     * @return The bytes for userTel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserTelBytes() {
      java.lang.Object ref = userTel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userTel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USEREMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object userEmail_;
    /**
     * <code>optional string userEmail = 4;</code>
     * @return Whether the userEmail field is set.
     */
    @java.lang.Override
    public boolean hasUserEmail() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string userEmail = 4;</code>
     * @return The userEmail.
     */
    @java.lang.Override
    public java.lang.String getUserEmail() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userEmail_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userEmail = 4;</code>
     * @return The bytes for userEmail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserEmailBytes() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERPASSWORD_FIELD_NUMBER = 5;
    private volatile java.lang.Object userPassword_;
    /**
     * <code>optional string userPassword = 5;</code>
     * @return Whether the userPassword field is set.
     */
    @java.lang.Override
    public boolean hasUserPassword() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string userPassword = 5;</code>
     * @return The userPassword.
     */
    @java.lang.Override
    public java.lang.String getUserPassword() {
      java.lang.Object ref = userPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPassword_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userPassword = 5;</code>
     * @return The bytes for userPassword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserPasswordBytes() {
      java.lang.Object ref = userPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERTYPE_FIELD_NUMBER = 6;
    private boolean userType_;
    /**
     * <code>optional bool userType = 6;</code>
     * @return Whether the userType field is set.
     */
    @java.lang.Override
    public boolean hasUserType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool userType = 6;</code>
     * @return The userType.
     */
    @java.lang.Override
    public boolean getUserType() {
      return userType_;
    }

    public static final int USERMONEY_FIELD_NUMBER = 7;
    private double userMoney_;
    /**
     * <code>optional double userMoney = 7;</code>
     * @return Whether the userMoney field is set.
     */
    @java.lang.Override
    public boolean hasUserMoney() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional double userMoney = 7;</code>
     * @return The userMoney.
     */
    @java.lang.Override
    public double getUserMoney() {
      return userMoney_;
    }

    public static final int USERCOMPANY_FIELD_NUMBER = 8;
    private volatile java.lang.Object userCompany_;
    /**
     * <code>optional string userCompany = 8;</code>
     * @return Whether the userCompany field is set.
     */
    @java.lang.Override
    public boolean hasUserCompany() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string userCompany = 8;</code>
     * @return The userCompany.
     */
    @java.lang.Override
    public java.lang.String getUserCompany() {
      java.lang.Object ref = userCompany_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userCompany_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userCompany = 8;</code>
     * @return The bytes for userCompany.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserCompanyBytes() {
      java.lang.Object ref = userCompany_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userCompany_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERHOME_FIELD_NUMBER = 9;
    private volatile java.lang.Object userHome_;
    /**
     * <code>optional string userHome = 9;</code>
     * @return Whether the userHome field is set.
     */
    @java.lang.Override
    public boolean hasUserHome() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string userHome = 9;</code>
     * @return The userHome.
     */
    @java.lang.Override
    public java.lang.String getUserHome() {
      java.lang.Object ref = userHome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userHome_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userHome = 9;</code>
     * @return The bytes for userHome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserHomeBytes() {
      java.lang.Object ref = userHome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userHome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERIP_FIELD_NUMBER = 10;
    private volatile java.lang.Object userIp_;
    /**
     * <code>optional string userIp = 10;</code>
     * @return Whether the userIp field is set.
     */
    @java.lang.Override
    public boolean hasUserIp() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional string userIp = 10;</code>
     * @return The userIp.
     */
    @java.lang.Override
    public java.lang.String getUserIp() {
      java.lang.Object ref = userIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIp_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userIp = 10;</code>
     * @return The bytes for userIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIpBytes() {
      java.lang.Object ref = userIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERPOS_FIELD_NUMBER = 11;
    private volatile java.lang.Object userPos_;
    /**
     * <code>optional string userPos = 11;</code>
     * @return Whether the userPos field is set.
     */
    @java.lang.Override
    public boolean hasUserPos() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional string userPos = 11;</code>
     * @return The userPos.
     */
    @java.lang.Override
    public java.lang.String getUserPos() {
      java.lang.Object ref = userPos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPos_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userPos = 11;</code>
     * @return The bytes for userPos.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserPosBytes() {
      java.lang.Object ref = userPos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userTel_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userEmail_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userPassword_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(6, userType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeDouble(7, userMoney_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userCompany_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, userHome_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, userIp_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, userPos_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userTel_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userEmail_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userPassword_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, userType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, userMoney_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userCompany_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, userHome_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, userIp_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, userPos_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoginProto.User)) {
        return super.equals(obj);
      }
      LoginProto.User other = (LoginProto.User) obj;

      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (getUserId()
            != other.getUserId()) return false;
      }
      if (hasUserName() != other.hasUserName()) return false;
      if (hasUserName()) {
        if (!getUserName()
            .equals(other.getUserName())) return false;
      }
      if (hasUserTel() != other.hasUserTel()) return false;
      if (hasUserTel()) {
        if (!getUserTel()
            .equals(other.getUserTel())) return false;
      }
      if (hasUserEmail() != other.hasUserEmail()) return false;
      if (hasUserEmail()) {
        if (!getUserEmail()
            .equals(other.getUserEmail())) return false;
      }
      if (hasUserPassword() != other.hasUserPassword()) return false;
      if (hasUserPassword()) {
        if (!getUserPassword()
            .equals(other.getUserPassword())) return false;
      }
      if (hasUserType() != other.hasUserType()) return false;
      if (hasUserType()) {
        if (getUserType()
            != other.getUserType()) return false;
      }
      if (hasUserMoney() != other.hasUserMoney()) return false;
      if (hasUserMoney()) {
        if (java.lang.Double.doubleToLongBits(getUserMoney())
            != java.lang.Double.doubleToLongBits(
                other.getUserMoney())) return false;
      }
      if (hasUserCompany() != other.hasUserCompany()) return false;
      if (hasUserCompany()) {
        if (!getUserCompany()
            .equals(other.getUserCompany())) return false;
      }
      if (hasUserHome() != other.hasUserHome()) return false;
      if (hasUserHome()) {
        if (!getUserHome()
            .equals(other.getUserHome())) return false;
      }
      if (hasUserIp() != other.hasUserIp()) return false;
      if (hasUserIp()) {
        if (!getUserIp()
            .equals(other.getUserIp())) return false;
      }
      if (hasUserPos() != other.hasUserPos()) return false;
      if (hasUserPos()) {
        if (!getUserPos()
            .equals(other.getUserPos())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserId()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId();
      }
      if (hasUserName()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
      }
      if (hasUserTel()) {
        hash = (37 * hash) + USERTEL_FIELD_NUMBER;
        hash = (53 * hash) + getUserTel().hashCode();
      }
      if (hasUserEmail()) {
        hash = (37 * hash) + USEREMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getUserEmail().hashCode();
      }
      if (hasUserPassword()) {
        hash = (37 * hash) + USERPASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getUserPassword().hashCode();
      }
      if (hasUserType()) {
        hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUserType());
      }
      if (hasUserMoney()) {
        hash = (37 * hash) + USERMONEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getUserMoney()));
      }
      if (hasUserCompany()) {
        hash = (37 * hash) + USERCOMPANY_FIELD_NUMBER;
        hash = (53 * hash) + getUserCompany().hashCode();
      }
      if (hasUserHome()) {
        hash = (37 * hash) + USERHOME_FIELD_NUMBER;
        hash = (53 * hash) + getUserHome().hashCode();
      }
      if (hasUserIp()) {
        hash = (37 * hash) + USERIP_FIELD_NUMBER;
        hash = (53 * hash) + getUserIp().hashCode();
      }
      if (hasUserPos()) {
        hash = (37 * hash) + USERPOS_FIELD_NUMBER;
        hash = (53 * hash) + getUserPos().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoginProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoginProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoginProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        LoginProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoginProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoginProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoginProto.User.class, LoginProto.User.Builder.class);
      }

      // Construct using LoginProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userTel_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        userEmail_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        userPassword_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        userType_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        userMoney_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        userCompany_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        userHome_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        userIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        userPos_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoginProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      public LoginProto.User getDefaultInstanceForType() {
        return LoginProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public LoginProto.User build() {
        LoginProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LoginProto.User buildPartial() {
        LoginProto.User result = new LoginProto.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userTel_ = userTel_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userEmail_ = userEmail_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userPassword_ = userPassword_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.userType_ = userType_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.userMoney_ = userMoney_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.userCompany_ = userCompany_;
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.userHome_ = userHome_;
        if (((from_bitField0_ & 0x00000200) != 0)) {
          to_bitField0_ |= 0x00000200;
        }
        result.userIp_ = userIp_;
        if (((from_bitField0_ & 0x00000400) != 0)) {
          to_bitField0_ |= 0x00000400;
        }
        result.userPos_ = userPos_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoginProto.User) {
          return mergeFrom((LoginProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoginProto.User other) {
        if (other == LoginProto.User.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasUserTel()) {
          bitField0_ |= 0x00000004;
          userTel_ = other.userTel_;
          onChanged();
        }
        if (other.hasUserEmail()) {
          bitField0_ |= 0x00000008;
          userEmail_ = other.userEmail_;
          onChanged();
        }
        if (other.hasUserPassword()) {
          bitField0_ |= 0x00000010;
          userPassword_ = other.userPassword_;
          onChanged();
        }
        if (other.hasUserType()) {
          setUserType(other.getUserType());
        }
        if (other.hasUserMoney()) {
          setUserMoney(other.getUserMoney());
        }
        if (other.hasUserCompany()) {
          bitField0_ |= 0x00000080;
          userCompany_ = other.userCompany_;
          onChanged();
        }
        if (other.hasUserHome()) {
          bitField0_ |= 0x00000100;
          userHome_ = other.userHome_;
          onChanged();
        }
        if (other.hasUserIp()) {
          bitField0_ |= 0x00000200;
          userIp_ = other.userIp_;
          onChanged();
        }
        if (other.hasUserPos()) {
          bitField0_ |= 0x00000400;
          userPos_ = other.userPos_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoginProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoginProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>optional int32 userId = 1;</code>
       * @return Whether the userId field is set.
       */
      @java.lang.Override
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>optional string userName = 2;</code>
       * @return Whether the userName field is set.
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string userName = 2;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userName = 2;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userName = 2;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 2;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userTel_ = "";
      /**
       * <code>optional string userTel = 3;</code>
       * @return Whether the userTel field is set.
       */
      public boolean hasUserTel() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string userTel = 3;</code>
       * @return The userTel.
       */
      public java.lang.String getUserTel() {
        java.lang.Object ref = userTel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userTel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userTel = 3;</code>
       * @return The bytes for userTel.
       */
      public com.google.protobuf.ByteString
          getUserTelBytes() {
        java.lang.Object ref = userTel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userTel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userTel = 3;</code>
       * @param value The userTel to set.
       * @return This builder for chaining.
       */
      public Builder setUserTel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userTel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userTel = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserTel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userTel_ = getDefaultInstance().getUserTel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userTel = 3;</code>
       * @param value The bytes for userTel to set.
       * @return This builder for chaining.
       */
      public Builder setUserTelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        userTel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userEmail_ = "";
      /**
       * <code>optional string userEmail = 4;</code>
       * @return Whether the userEmail field is set.
       */
      public boolean hasUserEmail() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string userEmail = 4;</code>
       * @return The userEmail.
       */
      public java.lang.String getUserEmail() {
        java.lang.Object ref = userEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userEmail = 4;</code>
       * @return The bytes for userEmail.
       */
      public com.google.protobuf.ByteString
          getUserEmailBytes() {
        java.lang.Object ref = userEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userEmail = 4;</code>
       * @param value The userEmail to set.
       * @return This builder for chaining.
       */
      public Builder setUserEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userEmail = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserEmail() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userEmail_ = getDefaultInstance().getUserEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userEmail = 4;</code>
       * @param value The bytes for userEmail to set.
       * @return This builder for chaining.
       */
      public Builder setUserEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000008;
        userEmail_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPassword_ = "";
      /**
       * <code>optional string userPassword = 5;</code>
       * @return Whether the userPassword field is set.
       */
      public boolean hasUserPassword() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string userPassword = 5;</code>
       * @return The userPassword.
       */
      public java.lang.String getUserPassword() {
        java.lang.Object ref = userPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userPassword = 5;</code>
       * @return The bytes for userPassword.
       */
      public com.google.protobuf.ByteString
          getUserPasswordBytes() {
        java.lang.Object ref = userPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userPassword = 5;</code>
       * @param value The userPassword to set.
       * @return This builder for chaining.
       */
      public Builder setUserPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userPassword = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserPassword() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userPassword_ = getDefaultInstance().getUserPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userPassword = 5;</code>
       * @param value The bytes for userPassword to set.
       * @return This builder for chaining.
       */
      public Builder setUserPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000010;
        userPassword_ = value;
        onChanged();
        return this;
      }

      private boolean userType_ ;
      /**
       * <code>optional bool userType = 6;</code>
       * @return Whether the userType field is set.
       */
      @java.lang.Override
      public boolean hasUserType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool userType = 6;</code>
       * @return The userType.
       */
      @java.lang.Override
      public boolean getUserType() {
        return userType_;
      }
      /**
       * <code>optional bool userType = 6;</code>
       * @param value The userType to set.
       * @return This builder for chaining.
       */
      public Builder setUserType(boolean value) {
        bitField0_ |= 0x00000020;
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool userType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        userType_ = false;
        onChanged();
        return this;
      }

      private double userMoney_ ;
      /**
       * <code>optional double userMoney = 7;</code>
       * @return Whether the userMoney field is set.
       */
      @java.lang.Override
      public boolean hasUserMoney() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional double userMoney = 7;</code>
       * @return The userMoney.
       */
      @java.lang.Override
      public double getUserMoney() {
        return userMoney_;
      }
      /**
       * <code>optional double userMoney = 7;</code>
       * @param value The userMoney to set.
       * @return This builder for chaining.
       */
      public Builder setUserMoney(double value) {
        bitField0_ |= 0x00000040;
        userMoney_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double userMoney = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserMoney() {
        bitField0_ = (bitField0_ & ~0x00000040);
        userMoney_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object userCompany_ = "";
      /**
       * <code>optional string userCompany = 8;</code>
       * @return Whether the userCompany field is set.
       */
      public boolean hasUserCompany() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional string userCompany = 8;</code>
       * @return The userCompany.
       */
      public java.lang.String getUserCompany() {
        java.lang.Object ref = userCompany_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userCompany_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userCompany = 8;</code>
       * @return The bytes for userCompany.
       */
      public com.google.protobuf.ByteString
          getUserCompanyBytes() {
        java.lang.Object ref = userCompany_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userCompany_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userCompany = 8;</code>
       * @param value The userCompany to set.
       * @return This builder for chaining.
       */
      public Builder setUserCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        userCompany_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userCompany = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserCompany() {
        bitField0_ = (bitField0_ & ~0x00000080);
        userCompany_ = getDefaultInstance().getUserCompany();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userCompany = 8;</code>
       * @param value The bytes for userCompany to set.
       * @return This builder for chaining.
       */
      public Builder setUserCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000080;
        userCompany_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userHome_ = "";
      /**
       * <code>optional string userHome = 9;</code>
       * @return Whether the userHome field is set.
       */
      public boolean hasUserHome() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional string userHome = 9;</code>
       * @return The userHome.
       */
      public java.lang.String getUserHome() {
        java.lang.Object ref = userHome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userHome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userHome = 9;</code>
       * @return The bytes for userHome.
       */
      public com.google.protobuf.ByteString
          getUserHomeBytes() {
        java.lang.Object ref = userHome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userHome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userHome = 9;</code>
       * @param value The userHome to set.
       * @return This builder for chaining.
       */
      public Builder setUserHome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        userHome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userHome = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserHome() {
        bitField0_ = (bitField0_ & ~0x00000100);
        userHome_ = getDefaultInstance().getUserHome();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userHome = 9;</code>
       * @param value The bytes for userHome to set.
       * @return This builder for chaining.
       */
      public Builder setUserHomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000100;
        userHome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userIp_ = "";
      /**
       * <code>optional string userIp = 10;</code>
       * @return Whether the userIp field is set.
       */
      public boolean hasUserIp() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional string userIp = 10;</code>
       * @return The userIp.
       */
      public java.lang.String getUserIp() {
        java.lang.Object ref = userIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userIp = 10;</code>
       * @return The bytes for userIp.
       */
      public com.google.protobuf.ByteString
          getUserIpBytes() {
        java.lang.Object ref = userIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userIp = 10;</code>
       * @param value The userIp to set.
       * @return This builder for chaining.
       */
      public Builder setUserIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        userIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userIp = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserIp() {
        bitField0_ = (bitField0_ & ~0x00000200);
        userIp_ = getDefaultInstance().getUserIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userIp = 10;</code>
       * @param value The bytes for userIp to set.
       * @return This builder for chaining.
       */
      public Builder setUserIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000200;
        userIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPos_ = "";
      /**
       * <code>optional string userPos = 11;</code>
       * @return Whether the userPos field is set.
       */
      public boolean hasUserPos() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional string userPos = 11;</code>
       * @return The userPos.
       */
      public java.lang.String getUserPos() {
        java.lang.Object ref = userPos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPos_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userPos = 11;</code>
       * @return The bytes for userPos.
       */
      public com.google.protobuf.ByteString
          getUserPosBytes() {
        java.lang.Object ref = userPos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userPos = 11;</code>
       * @param value The userPos to set.
       * @return This builder for chaining.
       */
      public Builder setUserPos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        userPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userPos = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserPos() {
        bitField0_ = (bitField0_ & ~0x00000400);
        userPos_ = getDefaultInstance().getUserPos();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userPos = 11;</code>
       * @param value The bytes for userPos to set.
       * @return This builder for chaining.
       */
      public Builder setUserPosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000400;
        userPos_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final LoginProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginProto.User();
    }

    public static LoginProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LoginProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *登录方式 0--&gt;电话登录  1--&gt;邮箱登录 ...
     * </pre>
     *
     * <code>int32 loginType = 1;</code>
     * @return The loginType.
     */
    int getLoginType();

    /**
     * <pre>
     *用户信息
     * </pre>
     *
     * <code>.User user = 2;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <pre>
     *用户信息
     * </pre>
     *
     * <code>.User user = 2;</code>
     * @return The user.
     */
    LoginProto.User getUser();
    /**
     * <pre>
     *用户信息
     * </pre>
     *
     * <code>.User user = 2;</code>
     */
    LoginProto.UserOrBuilder getUserOrBuilder();
  }
  /**
   * Protobuf type {@code Login}
   */
  public static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Login)
      LoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Login();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              loginType_ = input.readInt32();
              break;
            }
            case 18: {
              LoginProto.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(LoginProto.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoginProto.internal_static_Login_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoginProto.internal_static_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoginProto.Login.class, LoginProto.Login.Builder.class);
    }

    public static final int LOGINTYPE_FIELD_NUMBER = 1;
    private int loginType_;
    /**
     * <pre>
     *登录方式 0--&gt;电话登录  1--&gt;邮箱登录 ...
     * </pre>
     *
     * <code>int32 loginType = 1;</code>
     * @return The loginType.
     */
    @java.lang.Override
    public int getLoginType() {
      return loginType_;
    }

    public static final int USER_FIELD_NUMBER = 2;
    private LoginProto.User user_;
    /**
     * <pre>
     *用户信息
     * </pre>
     *
     * <code>.User user = 2;</code>
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <pre>
     *用户信息
     * </pre>
     *
     * <code>.User user = 2;</code>
     * @return The user.
     */
    @java.lang.Override
    public LoginProto.User getUser() {
      return user_ == null ? LoginProto.User.getDefaultInstance() : user_;
    }
    /**
     * <pre>
     *用户信息
     * </pre>
     *
     * <code>.User user = 2;</code>
     */
    @java.lang.Override
    public LoginProto.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (loginType_ != 0) {
        output.writeInt32(1, loginType_);
      }
      if (user_ != null) {
        output.writeMessage(2, getUser());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (loginType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, loginType_);
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUser());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoginProto.Login)) {
        return super.equals(obj);
      }
      LoginProto.Login other = (LoginProto.Login) obj;

      if (getLoginType()
          != other.getLoginType()) return false;
      if (hasUser() != other.hasUser()) return false;
      if (hasUser()) {
        if (!getUser()
            .equals(other.getUser())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOGINTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLoginType();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoginProto.Login parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginProto.Login parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginProto.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginProto.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginProto.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginProto.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginProto.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginProto.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginProto.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoginProto.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginProto.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginProto.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoginProto.Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Login)
        LoginProto.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoginProto.internal_static_Login_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoginProto.internal_static_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoginProto.Login.class, LoginProto.Login.Builder.class);
      }

      // Construct using LoginProto.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        loginType_ = 0;

        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoginProto.internal_static_Login_descriptor;
      }

      @java.lang.Override
      public LoginProto.Login getDefaultInstanceForType() {
        return LoginProto.Login.getDefaultInstance();
      }

      @java.lang.Override
      public LoginProto.Login build() {
        LoginProto.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LoginProto.Login buildPartial() {
        LoginProto.Login result = new LoginProto.Login(this);
        result.loginType_ = loginType_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoginProto.Login) {
          return mergeFrom((LoginProto.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoginProto.Login other) {
        if (other == LoginProto.Login.getDefaultInstance()) return this;
        if (other.getLoginType() != 0) {
          setLoginType(other.getLoginType());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoginProto.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoginProto.Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int loginType_ ;
      /**
       * <pre>
       *登录方式 0--&gt;电话登录  1--&gt;邮箱登录 ...
       * </pre>
       *
       * <code>int32 loginType = 1;</code>
       * @return The loginType.
       */
      @java.lang.Override
      public int getLoginType() {
        return loginType_;
      }
      /**
       * <pre>
       *登录方式 0--&gt;电话登录  1--&gt;邮箱登录 ...
       * </pre>
       *
       * <code>int32 loginType = 1;</code>
       * @param value The loginType to set.
       * @return This builder for chaining.
       */
      public Builder setLoginType(int value) {
        
        loginType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *登录方式 0--&gt;电话登录  1--&gt;邮箱登录 ...
       * </pre>
       *
       * <code>int32 loginType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginType() {
        
        loginType_ = 0;
        onChanged();
        return this;
      }

      private LoginProto.User user_;
      private com.google.protobuf.SingleFieldBuilderV3<
          LoginProto.User, LoginProto.User.Builder, LoginProto.UserOrBuilder> userBuilder_;
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       * @return Whether the user field is set.
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       * @return The user.
       */
      public LoginProto.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? LoginProto.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       */
      public Builder setUser(LoginProto.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       */
      public Builder setUser(
          LoginProto.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       */
      public Builder mergeUser(LoginProto.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              LoginProto.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       */
      public LoginProto.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       */
      public LoginProto.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              LoginProto.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <pre>
       *用户信息
       * </pre>
       *
       * <code>.User user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          LoginProto.User, LoginProto.User.Builder, LoginProto.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              LoginProto.User, LoginProto.User.Builder, LoginProto.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Login)
    }

    // @@protoc_insertion_point(class_scope:Login)
    private static final LoginProto.Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginProto.Login();
    }

    public static LoginProto.Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      @java.lang.Override
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LoginProto.Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\"\230\003\n\004User\022\023\n\006userId\030\001 \001(\005H\000" +
      "\210\001\001\022\025\n\010userName\030\002 \001(\tH\001\210\001\001\022\024\n\007userTel\030\003 " +
      "\001(\tH\002\210\001\001\022\026\n\tuserEmail\030\004 \001(\tH\003\210\001\001\022\031\n\014user" +
      "Password\030\005 \001(\tH\004\210\001\001\022\025\n\010userType\030\006 \001(\010H\005\210" +
      "\001\001\022\026\n\tuserMoney\030\007 \001(\001H\006\210\001\001\022\030\n\013userCompan" +
      "y\030\010 \001(\tH\007\210\001\001\022\025\n\010userHome\030\t \001(\tH\010\210\001\001\022\023\n\006u" +
      "serIp\030\n \001(\tH\t\210\001\001\022\024\n\007userPos\030\013 \001(\tH\n\210\001\001B\t" +
      "\n\007_userIdB\013\n\t_userNameB\n\n\010_userTelB\014\n\n_u" +
      "serEmailB\017\n\r_userPasswordB\013\n\t_userTypeB\014" +
      "\n\n_userMoneyB\016\n\014_userCompanyB\013\n\t_userHom" +
      "eB\t\n\007_userIpB\n\n\010_userPos\"/\n\005Login\022\021\n\tlog" +
      "inType\030\001 \001(\005\022\023\n\004user\030\002 \001(\0132\005.UserB\014B\nLog" +
      "inProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "UserId", "UserName", "UserTel", "UserEmail", "UserPassword", "UserType", "UserMoney", "UserCompany", "UserHome", "UserIp", "UserPos", "UserId", "UserName", "UserTel", "UserEmail", "UserPassword", "UserType", "UserMoney", "UserCompany", "UserHome", "UserIp", "UserPos", });
    internal_static_Login_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_descriptor,
        new java.lang.String[] { "LoginType", "User", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
